### ISSUE TITLE
Can't delete my account

### ISSUE THREAD

**Issue by alexanderlperez** [mydnic/gitweet.io#191]
I'd like to delete my accountfrom gitweet.io, but the Delete Account button does nothing.

Instead the console shows a bunch of errors related to `show` not existing:

![image](https://user-images.githubusercontent.com/3683232/152611095-bafbe94c-f672-4077-8da9-0a92093a2355.png)

**Comment by mydnic** [comment]
Uh that's weird, I'll have a look

**Comment by mydnic** [comment]
Should be fixed now :)
